---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zlayatech-production
  namespace: traefik
spec:
  secretName: zlayatech-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.zlaya.tech"
  dnsNames:
  - "zlaya.tech"
  - "*.zlaya.tech"