apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.zlaya.tech

    [users]
    allow_sign_up = false
    allow_org_create = true
    auto_assign_org = true
    auto_assign_org_id = 1
    auto_assign_org_role = Viewer
    verify_email_enabled = false
    login_hint = email or username
    password_hint = password

    [auth.generic_oauth]
    enabled = true
    name = zitadel
    allow_sign_up = true

    client_id = 308308884169229215

    scopes = openid email profile offline_access roles 
    email_attribute_name = email
    login_attribute_path = username
    name_attribute_path = fullname

    auth_url = https://zitadel.zlaya.tech/oauth/v2/authorize
    token_url = https://zitadel.zlaya.tech/oauth/v2/token
    api_url = https://zitadel.zlaya.tech/oidc/v1/userinfo 
    use_pkce = true

    role_attribute_path = contains('"user-roles[*]"', 'monitoring') && 'Editor' || 'admin'
