apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
resources:
  - namespace.yaml
  - gluetun-sealed-secret.yaml
  - pvc-config.yaml
  - pv-smb.yaml
  - pvc-smb.yaml
  - deployment.yaml
  - service.yaml
  - oidc-middleware.yaml
  - ingress.yaml
