kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-qbittorrent-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: pv-qbittorrent-smb
  storageClassName: smb
