---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgCfyq5Uba+zsziMK+eXR+wDiyTl/MPHeFy339+5DdmIXbC+ruieWJWeLN/c2byeahuve/eV1omJaLFzNSK1x9gX0CO5XIcdJOdWADic/OiLhT5ujK299XQiNCbp4CGRUDOOcTphzrTUGYdRyZshr5EhXqJ5Cxni3E7Ox79aQ5KTyzchMj8WSiWier+CaOcBngJCjORrjLzP3KsqVReyZqXjFN92OncJ4Tltd7U2DAULsO+4w0rz3LNHK5RZFcH6X/nQg0rnnGnDvP8pWSx6bK1T0TKbIphartsCZsfMYy/IT86n/fqxR+igXonMGi+6RaBmyd/ox5mRTltrDuet9zeHhhWpwa7UaOYYUyzRn/0CaLE7S804bOCcgzROg4z48dDlVpUw8z5xYSqp1kUpRCKWuazJ1NJXEmb8h+RIbgjczsnervGhmZDnbnR4AUUlsXeWj7VKaExw9KDAykkxTBhs/mFYwTarYrQJvAp+dNRGFTY4NRqNtV15b4J3SJgF6h6UtL82rgXGBCdFmaFn023Aun3cOMg6EcNTFHI+sG8vk2qWqY7eJHe5gPFVCCn+AqEEXOMOIoBOC3VHgVNUd7j1KaI/iRiKCXL6litLeY12wDDbX8Rj2QZxKalH/bTBBgRQxGtaAKM3bgFtgvjrCO3P14AZBVIjWZwkhmOg5MbPKHEBHN8b17PZ2CiJ28U5Y1CDBoUp2OoZO/MvzWc=
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque
