zitadel:
  masterkeySecretName: zitadel-masterkey
  namespace: zitadel
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: zitadel.zlaya.tech
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: db-postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: verify-full
        Admin:
          Username: postgres
          SSL:
            Mode: verify-full

  configSecretName: zitadel-secrets
  configSecretKey: config.yaml

  dbSslCaCrtSecret: postgres-cert
  dbSslAdminCrtSecret: postgres-cert
  dbSslUserCrtSecret: zitadel-cert