---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zitadel-secrets
  namespace: zitadel
spec:
  encryptedData:
    config.yaml: AgBPsYAMYuwEVTJTi0cYSAMNX2Ary7T0FO0t1oIV2VA/I3HzjQDeOkDN+SC+1NOSADSlHsuypauHQobhDAr8ms2E5TH2qT81niwXjKoYC9lnnFD9GuCSQ9HxI5OU9lCzWi8dfPQ4Ui/irSCg95A+7ZDuDKG/xSVuk4sUClp3O1R4E89RfjDbqv7Di30lrNwRlqWu8YHxq4BzkI5KlKoRYNji/fzQFmXkddMA9WMeoeOgOwZu+TWIKWovvMzZnZYQye2zWJW+b0luCnNI/WrGxN5w8lYgvqyc1qFYnV/wpzTxDj3R7ciFoJsvSbxBlUh3Llp1f9EhZZU9ADah24KsxVzfagbqHBq41U2WJbiYZpSvxF5AgcZscPdhRJAGy9frvP0S52mgD9La94oraZNe5VsXlEC6IT2RyNoLJSWrvU6NBva+ipd2ZQlBklQQazm4jLPlu1gTHlDZ5uUTQvkRU2xHTdeSYWX78QbTCJCVD2B8p33u8h2pgdLpJGLTce66Semh6K8+brbajTA7Yl4g848ukeYOdSmOsa/XrITxuypIrWDUtQoVCbzz4o2sgmKgZ7dIXm1KixrpyCUCvT2gEIPOea6SHlsM6olBBaeTrEwkZ+Tugx1dH88kzUiRA5EnAP4HL7Gp2OFE4iAferWueh7zHnuA/ORzOKmVZqXKehKV9pHISPZiKxFWnXRTe+f/dXJ2ikh+7f0Qzclj3ZMndI6EL/eLgIjygOSes+eq7D56M95bZwFoqqFwAe8w58Uwe2IWSwJIZE5qmkRbDK+t0AH18O99Ccufxoh+s+5siPsrrHIhsNnHO/CzPmgALGVF0mIxzAD27x1qoTI=
  template:
    metadata:
      creationTimestamp: null
      name: zitadel-secrets
      namespace: zitadel
    type: Opaque
