apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarr
resources:
  - namespace.yaml
  - pvc-config.yaml
  - pv-smb.yaml
  - pvc-smb.yaml
  - deployment.yaml
  - service.yaml
  - oidc-middleware.yaml
  - ingress.yaml
