apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    layout:
      Media:
        icon: mdi-television-play
        style: row
        columns: 3
      Servers:
        icon: mdi-server
        style: row
        columns: 3 
      Monitoring:
        icon: mdi-chart-box
        style: row
        columns: 3
      Group_1:
        header: false
        style: row
        columns: 4
        Management:
          icon: mdi-application-cog
          style: column
        Network:
          icon: mdi-network
          style: column
        Downloaders:
          icon: mdi-download
          style: column
        Security:
          icon: mdi-shield-check
          style: column      
    useEqualHeights: true
    theme: dark
    color: 
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Media:
        - Plex:
            icon: plex.png
            href: {{HOMEPAGE_VAR_PLEX_URL}}
            widget:
              type: plex
              url: {{HOMEPAGE_VAR_PLEX_URL}}
              key: {{HOMEPAGE_VAR_PLEX_KEY}}
        - Radarr:
            icon: radarr.png
            href: {{HOMEPAGE_VAR_RADARR_URL}}
            widget:
              type: radarr
              url: http://radarr.radarr.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_KEY}}
        - Sonarr:
            icon: sonarr.png
            href: {{HOMEPAGE_VAR_SONARR_URL}}
            widget:
              type: sonarr
              url: http://sonarr.sonarr.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_SONARR_KEY}}
        - Prowlarr:
            icon: prowlarr.png
            href: {{HOMEPAGE_VAR_PROWLARR_URL}}
            widget:
              type: prowlarr
              url: http://prowlarr.prowlarr.svc.cluster.local:9696
              key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
        - Bazarr:
            icon: bazarr.png
            href: {{HOMEPAGE_VAR_BAZARR_URL}}
            widget:
              type: bazarr
              url: http://bazarr.bazarr.svc.cluster.local:6767
              key: {{HOMEPAGE_VAR_BAZARR_KEY}}
        - Tautulli:
            icon: tautulli.png
            href: https://tautulli.zlaya.tech
            widget:
              type: tautulli
              url: http://tautulli.tautulli.svc.cluster.local:8181
              key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
              enableUser: true
              showEpisodeNumber: true

    - Servers:
        - TrueNAS:
            icon: truenas-scale.png
            href: {{HOMEPAGE_VAR_TRUENAS_URL}}
            widget:
              type: truenas
              url: https://192.168.1.101
              key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
              enablePools: true
              nasType: scale
        - Proxmox (Apollo):
            icon: proxmox.png
            href: {{HOMEPAGE_VAR_PROXMOX_URL}}
            widget:
              type: proxmox
              url: https://192.168.1.70:8006
              username: api@pam!homepage
              password: {{HOMEPAGE_VAR_PROXMOX_KEY}}
        - Proxmox (Old):
            icon: proxmox.png
            href: {{HOMEPAGE_VAR_PROXMOX2_URL}}
            widget:
              type: proxmox
              url: https://192.168.1.68:8006
              username: api@pam!homepage
              password: {{HOMEPAGE_VAR_PROXMOX2_KEY}}
    - Monitoring:
          - Grafana:
              icon: grafana.png
              href: {{HOMEPAGE_VAR_GRAFANA_URL}}
              widget:
                type: grafana
                url: http://grafana.monitoring.svc.cluster.local:3000
                username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
                password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
          - Prometheus:
              icon: prometheus.png
              href: https://prometheus.zlaya.tech
              widget:
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local:80
          - Uptime Kuma:
              icon: uptime-kuma.png
              href: https://uptime.zlaya.tech
              widget:
                type: uptimekuma
                url: https://uptime.zlaya.tech
                slug: zlaya
   
    - Group_1:
        - Management:
            - Rancher:
                icon: rancher.png
                href: {{HOMEPAGE_VAR_RANCHER_URL}}
            - Portainer:
                icon: portainer.png
                href: {{HOMEPAGE_VAR_PORTAINER_URL}}
                widget:
                  type: portainer
                  url: http://192.168.1.69:9000
                  env: 1
                  key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
        - Network:
            - Router:
                icon: router.png
                href: https://192.168.1.1/
            - Traefik:
                icon: traefik.png
                href: {{HOMEPAGE_VAR_TRAEFIK_URL}}
        - Downloaders:
            - qBittorrent:
                icon: qbittorrent.png
                href: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
                widget:
                  type: qbittorrent
                  url: http://qbittorrent.torrent.svc.cluster.local:8080
                  username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
                  password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
                  enableLeachProgress: true
        - Security:
            - Zitadel:
                icon: zitadel.png
                href: {{HOMEPAGE_VAR_ZITADEL_URL}}
            - Vaultwarden:
                icon: vaultwarden.png
                href: https://vaultwarden.zlaya.tech
            - Crowdsec:
                icon: crowdsec.png
                href: https://crowdsec.zlaya.tech
                widget:
                  type: crowdsec
                  url: https://crowdsec-service.crowdsec.svc.cluster.local:8080
                  username: {{HOMEPAGE_VAR_CROWDSEC_USERNAME}}
                  password: {{HOMEPAGE_VAR_CROWDSEC_PASSWORD}}
             

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""