---
argument_specs:
  main:
    short_description: Setup k3s agents
    options:
      apiserver_endpoint:
        description: Virtual ip-address configured on each master
        required: true

      extra_agent_args:
        description: Extra arguments for agents nodes

      group_name_master:
        description: Name of the master group
        default: master

      k3s_token:
        description: Token used to communicate between masters

      proxy_env:
        type: dict
        description:
          - Internet proxy configurations.
          - See https://docs.k3s.io/advanced#configuring-an-http-proxy for details
        default: ~
        options:
          HTTP_PROXY:
            description: HTTP internet proxy
            required: true
          HTTPS_PROXY:
            description: HTTPS internet proxy
            required: true
          NO_PROXY:
            description: Addresses that will not use the proxies
            required: true

      systemd_dir:
        description: Path to systemd services
        default: /etc/systemd/system
