kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sonarr-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  volumeName: pv-sonarr-smb
  storageClassName: smb
