kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bazarr-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  volumeName: pv-bazarr-smb
  storageClassName: smb
