---
k3s_version: v1.31.3+k3s1
# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: Your/Timezone

# interface which will be used for flannel
flannel_iface: eth0

# enable kube-vip ARP broadcasts
kube_vip_arp: true

# image tag for kube-vip
kube_vip_tag_version: v0.8.7

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: 192.168.1.50

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: some-SUPER-DEDEUPER-secret-password

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: "{{ ansible_facts[flannel_iface]['ipv4']['address'] }}"

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# Basic k3s arguments
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
# the contents of the if block is also required if using calico or cilium
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik

extra_agent_args: >-
  {{ extra_args }}


# metallb type frr or native
metal_lb_type: native

# metallb mode layer2 or bgp
metal_lb_mode: layer2

# image tag for metal lb
metal_lb_speaker_tag_version: v0.14.8
metal_lb_controller_tag_version: v0.14.8

# metallb ip range for load balancer
metal_lb_ip_range: 192.168.1.120-192.168.1.140